# Generated by Django 5.2.4 on 2025-07-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_latitude_restaurant_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_sponsored',
            field=models.BooleanField(default=False),
        ),
    ]
