# Generated by Django 5.2.4 on 2025-07-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurant_is_sponsored'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='preparation_time',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
