# Generated by Django 5.2.4 on 2025-07-31 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurant_preparation_time_restaurant_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='budget_category',
            field=models.CharField(choices=[('$', 'Budget'), ('$$', 'Mid-range'), ('$$$', 'Premium'), ('$$$$', 'Luxury')], default='$', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
