# Generated by Django 5.2.4 on 2025-07-31 23:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_restaurant_budget_category_restaurant_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='close_time',
            field=models.TimeField(default=datetime.time(22, 0)),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='open_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
