# Generated by Django 5.2.4 on 2025-08-01 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_menuitemcategory_menuitem_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=1.2, max_digits=3),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='tag',
            field=models.CharField(blank=True, default='Healthy', max_length=100, null=True),
        ),
    ]
