# Generated by Django 5.2.4 on 2025-08-01 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_menuitemcategory_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
