# Generated by Django 5.2.4 on 2025-08-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_menuitem_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='budget_category',
            field=models.CharField(choices=[('$ Affordable', 'Budget'), ('$$ Pricy', 'Mid-range'), ('$$$ Quite Pricy ', 'Premium'), ('$$$$ Expensive', 'Luxury')], default='$ Affordable', max_length=50),
        ),
    ]
