# Generated by Django 5.2.4 on 2025-08-15 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_restaurant_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='business',
        ),
    ]
