# Generated by Django 5.2.4 on 2025-08-15 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sass', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='vendor',
        ),
        migrations.AddField(
            model_name='vendor',
            name='business_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sass.business'),
        ),
    ]
