# Generated by Django 5.2.4 on 2025-08-12 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sass', '0001_initial'),
        ('supermarkets', '0003_remove_product_category_remove_product_supermarket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supermarket',
            name='business',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supermarket_details', to='sass.business'),
        ),
    ]
